apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xiys7-poi-map-app-dev
  annotations:
    argocd/app-name: xiys7-poi-map-app-dev
    backstage.io/kubernetes-id: xiys7-poi-map-app
    backstage.io/kubernetes-namespace: xiys7
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/xiys7-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/xiys7/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/xiys7/deployments/xiys7-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/xiys7-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://xiys7-poi-map-app-xiys7.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/xiys7"
  system: workshop-system-xiys7
  consumesApis:
    - gateway-api-xiys7
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-xiys7
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/xiys7"
